"""customization

Revision ID: 9dda7c2dfaeb
Revises: 9c1ccf41ecb8
Create Date: 2024-04-13 16:19:03.201744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dda7c2dfaeb'
down_revision: Union[str, None] = '9c1ccf41ecb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('background_image', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('background_color', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('border_color', sa.String(), nullable=True))
    op.add_column('users', sa.Column('background_color', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notes_background_color', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notes_border_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notes_border_color')
    op.drop_column('users', 'notes_background_color')
    op.drop_column('users', 'background_color')
    op.drop_column('notes', 'border_color')
    op.drop_column('notes', 'background_color')
    op.drop_column('notes', 'background_image')
    # ### end Alembic commands ###
